export type GoldenTaskProfile = {
  id: string;
  title: string;
  platform: "ios" | "android" | "backend" | "cross-platform";
  purpose: string;
  requiredCapabilities: string[];
};

export const GENERIC_BENCHMARK_PROFILES: GoldenTaskProfile[] = [
  {
    id: "tanya.low.search-replace",
    title: "Low - Targeted Search Replace",
    platform: "cross-platform",
    purpose: "Update one existing source file with a precise replacement and verify the marker.",
    requiredCapabilities: ["read before edit", "search_replace", "bounded verification"],
  },
  {
    id: "tanya.low.new-helper",
    title: "Low - New Helper File",
    platform: "cross-platform",
    purpose: "Create a small helper module and verify it exists with expected content.",
    requiredCapabilities: ["write_file", "final report", "bounded verification"],
  },
  {
    id: "tanya.low.config-update",
    title: "Low - Config Update",
    platform: "cross-platform",
    purpose: "Update a simple JSON-like config file without touching unrelated files.",
    requiredCapabilities: ["targeted edit", "changed-file reporting", "bounded verification"],
  },
  {
    id: "tanya.low.readme-update",
    title: "Low - README Update",
    platform: "cross-platform",
    purpose: "Append a concise documentation note and verify the note is present.",
    requiredCapabilities: ["documentation edit", "artifact reuse none", "bounded verification"],
  },
  {
    id: "tanya.low.package-script",
    title: "Low - Package Script",
    platform: "cross-platform",
    purpose: "Add a package script while preserving existing package metadata.",
    requiredCapabilities: ["JSON edit", "package script reporting", "bounded verification"],
  },
  {
    id: "tanya.medium.service-module",
    title: "Medium - Service Module",
    platform: "cross-platform",
    purpose: "Create a service module and matching index export in a small multi-file change.",
    requiredCapabilities: ["multi-file edit", "verification", "complete report"],
  },
  {
    id: "tanya.medium.test-harness",
    title: "Medium - Test Harness",
    platform: "cross-platform",
    purpose: "Add a tiny executable test harness and verify it runs.",
    requiredCapabilities: ["test file creation", "run_command", "complete report"],
  },
  {
    id: "tanya.medium.artifact-component",
    title: "Medium - Artifact Component",
    platform: "cross-platform",
    purpose: "Read a reusable UI artifact and adapt it into a project component.",
    requiredCapabilities: ["artifact read", "artifact provenance", "multi-file report"],
  },
  {
    id: "tanya.medium.artifact-service",
    title: "Medium - Artifact Service",
    platform: "backend",
    purpose: "Read a reusable service artifact and adapt it into a project helper.",
    requiredCapabilities: ["artifact read", "artifact provenance", "bounded verification"],
  },
  {
    id: "tanya.medium.dirty-worktree",
    title: "Medium - Dirty Worktree",
    platform: "cross-platform",
    purpose: "Complete a task in a repo that already has unrelated uncommitted changes.",
    requiredCapabilities: ["git snapshot", "unrelated dirty preservation", "final report"],
  },
  {
    id: "tanya.medium.report-repair",
    title: "Medium - Report Repair",
    platform: "cross-platform",
    purpose: "Recover when the model initially omits the required coding final report.",
    requiredCapabilities: ["final report reminder", "repair loop", "verification preservation"],
  },
  {
    id: "tanya.medium.multi-file",
    title: "Medium - Multi-File Feature",
    platform: "cross-platform",
    purpose: "Create coordinated source and docs changes and verify both outputs.",
    requiredCapabilities: ["multi-file edit", "changed-file reporting", "bounded verification"],
  },
  {
    id: "tanya.medium.package-manager",
    title: "Medium - Package Manager Script",
    platform: "cross-platform",
    purpose: "Use a workspace script path that also exercises post-check package-manager detection.",
    requiredCapabilities: ["package metadata", "script verification", "post-check readiness"],
  },
  {
    id: "tanya.medium.context-aware",
    title: "Medium - Context-Aware Edit",
    platform: "cross-platform",
    purpose: "Read caller context before editing and preserve that provenance in the run.",
    requiredCapabilities: ["context read", "context provenance", "complete report"],
  },
  {
    id: "tanya.medium.existing-tests",
    title: "Medium - Existing Tests",
    platform: "cross-platform",
    purpose: "Modify implementation while running an existing local verification script.",
    requiredCapabilities: ["existing test command", "verification reporting", "changed-file reporting"],
  },
  {
    id: "tanya.medium.dependency-install",
    title: "Medium - Dependency Install",
    platform: "cross-platform",
    purpose: "Update package metadata and lockfile-style state while verifying dependency intent without network access.",
    requiredCapabilities: ["package manifest update", "lockfile update", "bounded verification"],
  },
  {
    id: "tanya.medium.framework-migration",
    title: "Medium - Framework Migration",
    platform: "cross-platform",
    purpose: "Move a small legacy page into an app-router-style layout while preserving a compatibility entrypoint.",
    requiredCapabilities: ["framework convention", "multi-file migration", "changed-file reporting"],
  },
  {
    id: "tanya.medium.failing-test-repair",
    title: "Medium - Failing Test Repair",
    platform: "cross-platform",
    purpose: "Observe a failing verification, repair the implementation, and rerun the same check successfully.",
    requiredCapabilities: ["failed verification recovery", "targeted edit", "verification rerun"],
  },
  {
    id: "tanya.medium.frontend-smoke",
    title: "Medium - Frontend Smoke",
    platform: "cross-platform",
    purpose: "Create a minimal component, styles, and smoke check that verifies rendered content markers.",
    requiredCapabilities: ["frontend files", "visual smoke proxy", "bounded verification"],
  },
  {
    id: "tanya.medium.run-log-history",
    title: "Medium - Usage Metrics Run Log",
    platform: "cross-platform",
    purpose: "Complete a normal edit while emitting usage counts that should be persisted to .tania/runs.",
    requiredCapabilities: ["usage metrics", "run log persistence", "history visibility"],
  },
  {
    id: "tanya.medium.streaming-long-tool",
    title: "Medium - Streaming Long Tool",
    platform: "cross-platform",
    purpose: "Run a >10s shell verification that streams progress while preserving the final tool result contract.",
    requiredCapabilities: ["tool_progress", "long-running run_shell", "provider-history isolation"],
  },
  {
    id: "tanya.medium.compaction-boundary",
    title: "Medium - Compaction Boundary",
    platform: "cross-platform",
    purpose: "Recover from a synthetic context-window failure mid-run and preserve the final verifier verdict.",
    requiredCapabilities: ["ContextWindowExceededError", "auto-compact retry", "archive-backed verifier surface"],
  },
  {
    id: "tanya.medium.edit-block-fuzzy",
    title: "Medium - Fuzzy Edit Block",
    platform: "cross-platform",
    purpose: "Recover a cheap-provider-style near-match with permission-gated fuzzy edit blocks while preserving verifier verdicts.",
    requiredCapabilities: ["edit_block", "fuzzy recovery", "permission-gated edit", "verifier parity"],
  },
];

export const BUILT_IN_GOLDEN_TASK_PROFILES: GoldenTaskProfile[] = [
  {
    id: "cosmohq.ios.setup-environment",
    title: "Setup Environment - iOS",
    platform: "ios",
    purpose: "Verify Fastlane/SwiftLint/project setup without false artifact or changed-file failures.",
    requiredCapabilities: ["artifact provenance", "xcodebuild verification", "commit reporting"],
  },
  {
    id: "cosmohq.android.setup-environment",
    title: "Setup Environment - Android",
    platform: "android",
    purpose: "Verify Gradle/Fastlane setup while preserving local SDK boundaries.",
    requiredCapabilities: ["Gradle verification", "local.properties protection", "commit reporting"],
  },
  {
    id: "cosmohq.ios.foundation",
    title: "Fundações - iOS",
    platform: "ios",
    purpose: "Create theme, SwiftData models, navigation, base UI states, and dark-mode support.",
    requiredCapabilities: ["iOS foundation validator", "artifact mapping", "font fallback policy", "xcodebuild verification"],
  },
  {
    id: "cosmohq.android.foundation",
    title: "Fundações - Android",
    platform: "android",
    purpose: "Create/preserve Material 3 theme, Room, Navigation Compose, and base composables.",
    requiredCapabilities: ["create_android_foundation", "preserve existing files", "ktlint/Gradle verification"],
  },
  {
    id: "cosmohq.ios.splash",
    title: "Splash Screen - iOS",
    platform: "ios",
    purpose: "Create a brand-compliant splash screen and SplashIcon asset without over-scoping other iOS foundation validators.",
    requiredCapabilities: ["create_ios_splash", "iOS splash validator", "artifact provenance"],
  },
  {
    id: "cosmohq.android.splash",
    title: "Splash Screen - Android",
    platform: "android",
    purpose: "Create or verify native AndroidX splash resources and Compose runtime splash.",
    requiredCapabilities: ["Android splash validator", "zero-change verification reporting", "Gradle verification"],
  },
  {
    id: "cosmohq.apple.app-icon",
    title: "App Icon - Apple",
    platform: "ios",
    purpose: "Generate iOS/iPad/macOS AppIcon slots and verify Contents.json programmatically.",
    requiredCapabilities: ["create_apple_app_icon_set", "programmatic Contents.json parse", "asset validation"],
  },
  {
    id: "cosmohq.backend.api-foundation",
    title: "Backend API Foundation",
    platform: "backend",
    purpose: "Implement backend API contracts while keeping brand/api_features route parity.",
    requiredCapabilities: ["API contract validation", "Prisma validation", "typecheck/test verification"],
  },
  ...GENERIC_BENCHMARK_PROFILES,
];
